---
title: "About me"
output: 
  html_document:
      toc: true
      toc_float: true
      theme: sandstone
---
# My resume
# Yuechen Liu
518-960-7017 | yuechenl1998@gmail.com | 50 Haven Ave, #G87, 10032, New York City

# Education

Rensselaer Polytechnic Institute - Troy, New York     August 2016-May 2020
BS in Biochemistry & Biophysics, with GPA of 3.33

Columbia University – New York, New York              August 2020-present
MS in Biostatistics—Theory and Method 

GRE (took in 2018): 327 (V159+Q168+W3.5)

# Skills & Abilities

-Basic laboratory skills: Titration, TLC plate, Purification, Liquid Extraction.
Western Blot, Microscopy (normal, fluorescent, dissecting), SDS PAGE, PCR, Column Chromatography, Genetic Engineering. 
-Communication skills: Fluent English & Mandarin (1st language)
-Software skills: PowerPoint, Word, Excel, COOT, Pymol, BLAST, VectorNTI, BioEQS, RStudio, MatLab -Other skills: Drawing

# Experience

Nanjing University – Nanjing, China， Summer 2018
Assisted laboratory work which focused on “The key target role of Act1 in TGF- β signaling and drug discovery for RA-ILD”.

Chunyu Wang lab, Rensselaer, New York, 2019-2020
Laboratory research based on Alzheimer-related protein including purification, MS,
NMR and cell culture technique.

JingLiXin Pharmaceutical Company – Nanjing, China, Summer 2019
A 2-month internship at this compa Ranitidine, SEROQUEL XR and cefixime. Major experiments done during the period: dissolution and HPLC.

Research Paper: Nanjing Forestry University
Assistant work for a paper based on “Effects of β-glucosidase and α-rhamnosidase on the Contents of Flavonoids, Ginkgolides, and Aroma Components in Ginkgo Tea Drink”, published on Molecules, 25 May 2019.









